### PR TITLE
Enable FIPS support

### PR DESCRIPTION
**Pull request by bsquizz**
Allows the selenium standalone image to run on a FIPS-enabled host.

* Enables FIPS mode for nss DB
* Upgrades to OpenJDK 11 and Selenium v4.8.1
* Sets the web driver HTTP client to be the Java HTTP Client instead of Netty, see https://www.selenium.dev/blog/2022/using-java11-httpclient/

### CODE REVIEW

**Comment by bsquizz** [comment]
I am not sure if turning this on will have impact when running on a non-FIPS host -- need to test and verify.

**Comment by bsquizz** [comment]
This gets us partly there but not 100%. When a request comes into the Selenium Distributor, it turns around and tries to make an HTTP request using a modified trust store, which is not permitted with FIPS enabled:

```
Starting Xvnc
Starting fluxbox
Starting selenium standalone
20:30:27.425 INFO [LogManager$RootLogger.log] - Using the system default encoding
20:30:27.429 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
20:30:28.807 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
20:30:28.827 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
20:30:28.853 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 1 times
20:30:28.854 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 1 times
20:30:28.979 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
20:30:29.117 INFO [GridModel.setAvailability] - Switching Node 76aa7e63-d7cc-46c1-971f-fadaa1a60a74 (uri: http://10.128.3.246:4444) from DOWN to UP
20:30:29.118 INFO [LocalDistributor.add] - Added node 76aa7e63-d7cc-46c1-971f-fadaa1a60a74 at http://10.128.3.246:4444. Health check every 120s
20:30:29.338 INFO [Standalone.execute] - Started Selenium Standalone 4.1.4 (revision 535d840ee2): http://10.128.3.246:4444
20:31:57.332 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, pageLoadStrategy: normal}]
1677702717354	geckodriver	INFO	Listening on 127.0.0.1:50093
Exception in thread "Local Distributor - Session Creation" java.lang.ExceptionInInitializerError
	at org.openqa.selenium.remote.http.netty.NettyClient$Factory.createClient(NettyClient.java:133)
	at org.openqa.selenium.remote.tracing.TracedHttpClient$Factory.createClient(TracedHttpClient.java:77)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:137)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:67)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:145)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:349)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:609)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:535)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:746)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:707)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Could not initialize sslEngineFactory
	at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:106)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:92)
	at org.asynchttpclient.Dsl.asyncHttpClient(Dsl.java:32)
	at org.openqa.selenium.remote.http.netty.NettyClient.createHttpClient(NettyClient.java:92)
	at org.openqa.selenium.remote.http.netty.NettyClient.<clinit>(NettyClient.java:47)
	... 13 more
Caused by: javax.net.ssl.SSLException: failed to initialize the client-side SSL context
	at io.netty.handler.ssl.JdkSslClientContext.newSSLContext(JdkSslClientContext.java:310)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:272)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:824)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:611)
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.buildSslContext(DefaultSslEngineFactory.java:59)
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.init(DefaultSslEngineFactory.java:74)
	at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:104)
	... 17 more
Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
	at sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)
	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:95)
	at javax.net.ssl.SSLContext.init(SSLContext.java:282)
	at io.netty.handler.ssl.JdkSslClientContext.newSSLContext(JdkSslClientContext.java:294)
	... 23 more
```

Perhaps switching away from the Netty HTTP client to the java HTTP client could make a difference here but not sure. https://www.selenium.dev/blog/2022/using-java11-httpclient/

**Comment by bsquizz** [comment]
I think this is the source of the error: https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/http/netty/NettyClient.java#L80

**Comment by bsquizz** [comment]
After swapping to the Java HTTP client, this image is working when running on both a FIPS and non-FIPS host

**Comment by LightOfHeaven1994** [comment]
Tested it with FF and Chrome, work as expected. Thanks!

**Pull request merged**
